#!/usr/bin/perl -w

die "Need an argument." if !defined($ARGV[0]);
$N = $ARGV[0];

for ($m1=2;$m1<=$N;$m1+=2) { for($m2=2;$m2<$m1;$m2+=2) {
  if ($m1%3==0 || $m2%3==0 || $m1%3==$m2%3) {
    print "$m1 $m2\n";
  }
}}
