#!/usr/bin/perl

while(<>) {
  if (/The number of primes p less than (\d)([\d\,]+)/) {
    $temp1 = $1;
    $temp2 = $2;
    $power = 0;
    while ($temp2 =~ s/0//) {$power++}
    if ($temp1==1) {
      $power = "10<sup>$power</sup>";
    } else {
      $power = "$temp1.10<sup>$power</sup>";
    }
    $powerlist[$p] = $power;
    $p++;
  }
  if (/prime is/) {
    $diff = "";
    while (s/p\-(\d+)//) {$diff .= " $1"}
    $difflist{$diff} = $d;
    $d++;
    /(\d+)$/;
    $count{"$power$diff"} = $1;
  }
}

$p=$#powerlist+1;

print <<EOL;
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
   <meta name="GENERATOR" content="nedit">
   <meta name="Author" content="Stephen Montgomery-Smith">
   <title>Primes</title>
</head>
<body bgcolor="#FF99FF">

<h1><center>Numbers of Primes</center></h1>

The following table shows the number of primes <i>p</i> less than a given
number, for which 
<i>p</i>-<i>a</i><sub>1</sub>,
<i>p</i>-<i>a</i><sub>2</sub>,...,
<i>p</i>-<i>a</i><sub><i>k</i></sub>
are also prime, for selected sequences
<i>a</i><sub>1</sub>,
<i>a</i><sub>2</sub>,...,
<i>a</i><sub><i>k</i></sub>.&nbsp;

<p>
<table border="1">
<tr>
<th>&nbsp;</th>
<th colspan="$p">Number of primes less than:</th>
</tr>
<tr>
<th>Sequence</th>
EOL

foreach $power(@powerlist) {
  print "<th>$power</th>";
}
print "</tr>\n";

foreach $diff(sort {$difflist{$a}<=>$difflist{$b}} keys %difflist) {
  $temp = $diff;
  $temp =~ s/^\s+//;
  $temp =~ s/\s+/\,/g;
  print "<tr><th>$temp</th>";
  foreach $power(@powerlist) {
    print "<td align=\"right\">",$count{"$power$diff"},"</td>";
  }
  print "</tr>\n";
}

print "</table>\n";

print "</body>\n</html>\n";
