.\"
.\" Copyright (c) 2001, 2002 by Stephen Montgomery-Smith
 * <stephen@math.missouri.edu>
.\"
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted,
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in
.\" supporting documentation.
.\"
.\" This file is provided AS IS with no warranties of any kind.  The author
.\" shall have no liability with respect to the infringement of copyrights,
.\" trade secrets or any patents by this file or any part thereof.  In no
.\" event will the author be liable for any lost revenue or profits or
.\" other special, indirect and consequential damages.
.\"
.\"
.TH "ENACT" "1" "0.8" "Stephen Montgomery-Smith" ""
.SH "NAME"
enact \- distribute task over several computers
.SH "SYNOPSIS"
.B enact
[\-f]
[\-n \fInumber\fP]
[\-p]
\fIprogram\fP
\fIpass\-key\fP
\fIhostname\fP
\fIport\-nr\fP
\fItimeout\fP
.SH "DESCRIPTION"
This program is used, with \fBdispense(1)\fP, to distribute a task over several computers.
.SH "OPTIONS"
.PP 
.TP 
.B \-f
Run \fBenact\fP in the foreground (the default is for it to run as a daemon).
.PP 
.TP 
.B \-n \fInumber\fP
Set the "nice" level.
.PP 
.TP 
.B \-p
\fBenact\fP will open \fIprogram-name\fP using a pseudo terminal, so that 
\fIprogram-name\fP automatically has line buffering for stdout.
.PP 
.TP 
.B \fIprogram\fP
The program that \fBenact\fP runs.
.PP 
.TP 
.B \fIpass\-key\fP
A password to make sure that the \fBenact\fP and \fBdispense\fP programs are 
working on the same problem.
.PP 
.TP 
.B \fIhostname\fP
The hostname of the computer that is running \fBdispense\fP.
.PP 
.TP 
.B \fIport\-nr\fP
The number of the port which \fBdispense\fP is listening to.

.SH "FOR MORE INFORMATION"
If this package proves popular to use, I will write a proper set of man pages.  In the mean time, read the file
.B README
that comes with the package.
.SH "SEE ALSO"
dispense(1), nice(1)
.SH "AUTHOR"
Stephen Montgomery\-Smith <stephen@math.missouri.edu>
