#!/usr/bin/perl -w

open(INDEX,"index.html");
$index = join '',<INDEX>;
close(INDEX);

$index =~ /(.*\<UL\>)(.*)(\<\/UL\>.*)/s;
$start = $1;
$middle = $2;
$end = $3;

open(INDEX,"> index2.html");
print INDEX $start;

@paperlist = split '<LI>',$middle;
$first = 1;
foreach $paper (@paperlist) {
  if ($paper =~ /\<A HREF\=\"([^\"]+)\.tex\"\>/ || $paper =~ /\<A HREF\=\"([^\"\/]+)\.pdf\"\>/ || $paper =~ /\&\#44\;\s+<A HREF\=\"([^\"]+)\.html\"\>\s*(\S+)/ || $paper =~ /\&\#44\;\s+(\S+)/) {
    print "$1\n";
    $name = $1;
    $name =~ s/\d+$//;
    $name =~ s/\_$//;
    $name =~ s/\-$//;
    $paper =~ s/^\n\<B\>(.*?)\<\/B\>//s;
    $title = $1;
    if ($title =~ s/(.*\&\#44\;\s+)//) {
      $authors = $1;
    }
    else {
      $authors = '';
    }
    print INDEX "<LI>" if !$first;
    $first = 0;
    print INDEX "\n<B>$authors";
    if ($title =~ /^\<A HREF/) {
      print INDEX $title;
    }
    else {
      print INDEX "<A HREF=\"$name.html\">$title</A>";
    }
    print INDEX "</B>$paper";
    open(PAPER,"> $name.html");
    $title = $1 if $title =~ /^\<A HREF\=\".*?\"\>(.*)\<\/A\>$/s;
    print PAPER <<EOM;
<HTML>
<HEAD>
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
   <META NAME="GENERATOR" CONTENT="A little perl program">
   <META NAME="Author" CONTENT="Stephen Montgomery-Smith">
   <TITLE>$title</TITLE>
   <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
   <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
</HEAD>
<BODY TEXT="#000000" BGCOLOR="#66FF99" LINK="#0000EE" VLINK="#551A8B" ALINK="#FF0000">

EOM
    $paper =~ s/\<\/LI\>//;
    print PAPER "<B>$authors$title</B>$paper";
    print PAPER <<EOM;
<P>&nbsp;
<CENTER>&nbsp;<A HREF="index.html">List of all preprints</A></CENTER>
&nbsp;
</BODY>   
</HTML>
EOM
    close PAPER;
  }
  else {
    print INDEX "<LI>" if !$first;
    $first = 0;
    print INDEX $paper;
  }
}

print INDEX $end;
