#!/usr/bin/perl -w

#/*
# * Copyright (c) 2001 by Stephen Montgomery-Smith <stephen@math.missouri.edu>
# *
# * Permission to use, copy, modify, and distribute this software and its
# * documentation for any purpose and without fee is hereby granted,
# * provided that the above copyright notice appear in all copies and that
# * both that copyright notice and this permission notice appear in
# * supporting documentation.
# *
# * This file is provided AS IS with no warranties of any kind.  The author
# * shall have no liability with respect to the infringement of copyrights,
# * trade secrets or any patents by this file or any part thereof.  In no
# * event will the author be liable for any lost revenue or profits or
# * other special, indirect and consequential damages.
# *
# */

use Socket;

while (<>) {
  if (/^Data from (\d+\.\d+\.\d+\.\d+)\:\d+/) {
    $ip{$1}++;
  }
}

foreach $key (sort {ipton($a)<=>ipton($b)} keys %ip) {
  $name = gethostbyaddr(inet_aton($key), AF_INET);
  if (defined($name)) {
    print "$name $key $ip{$key}\n";
  } else {
    print "$key $ip{$key}\n";
  }
}

sub ipton {
  @a = split /\./,$_[0];
  return $a[0]*65536*256+$a[1]*65536+$a[2]*256+$a[3];
}
